# Config for dependabot version updates

# Doco:
#   Configuration options for the dependabot.yml file
#     https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
#   Configuring Dependabot version updates
#     https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates

version: 2
updates:
  # Configuration for npm
  - package-ecosystem: "npm"
    directory: "/REST/PhotoFrame" # manifests for this project are not in the root directory
    schedule:
      interval: "daily"
